### ISSUE TITLE
smaller screen sizes create image overlap on the data upload screen

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/weeds-image-repo-app#22]
**What's wrong**
- we have different sized tablets and the smaller ones create an overlap of the cards on the data upload screen. i'll attach a screenshot when i get one from a tester

**What done looks like**
- dynamically resize cards based on screen height to avoid overlap

**Comment by ravighevariya10** [comment]
It's resolved now. There was a hard-coded width to the card view that I set to the match_parent and it is working fine on my tab
